### PR TITLE
Bug fix for Collaborative editor

### LINKED ISSUE #97: Bug: Editor details deleted when both users navigate out of the editor page
Steps to reproduce:
1. Both users in collab service
2. Users key in some text
3. Both users click on PeerPrep logo (Or any other ways to nav out)
4. User clicks return to room
5. Editor text is deleted

### PR DESCRIPTION
**Pull request by Pughal77**
Fixes the bug when both user leaves the room, the editor would be rerendered.
Now the editor does not rerender on dismount of the Collaborative Editor component

fixes #97

### CODE REVIEW

File: frontend/src/features/collaboration/components/CollaborativeEditor.tsx [hunk 1]
```diff
@@ -118,12 +128,16 @@ const CollaborativeEditor: React.FC<CollaborativeEditorProps> = ({ question, set
...
-        new MonacoBinding(yText, monacoEditorRef.current.getModel()!, new Set([monacoEditorRef.current]));
+        new MonacoBinding(
+            yText,
+            monacoEditorRef.current.getModel()!,
+            new Set([monacoEditorRef.current])
+        );
 
         return () => {
-            provider.destroy();
+            // provider.destroy();
```
Comment (seanpzk) [inline frontend/src/features/collaboration/components/CollaborativeEditor.tsx]: I think you may choose to delete the entire return function since it is not doing anything

**Review by seanpzk — APPROVED** [review]
LGTM

**Review by DonovanJJ — APPROVED** [review]
LGTM!
